version: "3.7"

services:
  docker-labs-pocketbase:
    container_name: docker-labs-pocketbase
    image: augustodelg/pocketbase
    restart: unless-stopped
    ports:
      - "10000:8090"
    volumes:
      - pocketbase-data:/pb_data

  docker-labs-user-client:
    container_name: docker-labs-user-client
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "10001:10001"
    volumes:
      - ./src:/app/src
      - ./static:/app/static

volumes:
  pocketbase-data: